/*
 * File: app/store/menuStore.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.store.menuStore', {
  extend: 'Ext.data.TreeStore',

  requires: [
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId: 'menuStore',
      root: {
        expanded: true,
        children: [
          {
            text: 'Dashboard',
            iconCls: 'x-fa fa-chart-pie',
            children: [
              {
                itemId: 'pnlVistaGeneral',
                text: 'Vista general',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              },
              {
                itemId: 'pnlTendencias',
                text: 'Tendencias',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              }
            ]
          },
          {
            text: 'Ingresos',
            iconCls: 'x-fas fa-money-bill',
            children: [
              {
                itemId: 'pnlDetalleIngresos',
                text: 'Detalle',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              }
            ]
          },
          {
            text: 'Gastos',
            iconCls: 'x-fas fa-hand-holding-usd',
            children: [
              {
                itemId: 'pnlDetalleGastos',
                text: 'Detalle',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              }
            ]
          },
          {
            text: 'Presupuesto',
            iconCls: 'x-fas fa-piggy-bank',
            children: [
              {
                itemId: 'pnlDetallePresupuesto',
                text: 'Detalle',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              },
              {
                itemId: 'pnlComparacion',
                text: 'Comparación',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              }
            ]
          },
          {
            text: 'Metas',
            iconCls: 'x-fa fa-bullseye',
            children: [
              {
                itemId: 'pnlDetalleMetas',
                text: 'Detalle',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              },
              {
                itemId: 'pnlProgreso',
                text: 'Progreso',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              }
            ]
          },
          {
            text: 'Configuración',
            iconCls: 'x-fa fa-cog',
            children: [
              {
                itemId: 'pnlCategorias',
                text: 'Categorías',
                iconCls: 'x-fa fa-genderless',
                leaf: true
              }
            ]
          },
          {
            itemId: 'exit',
            text: 'Salir',
            iconCls: 'x-fa fa-times-circle',
            leaf: true
          }
        ]
      },
      proxy: {
        type: 'ajax',
        reader: {
          type: 'json'
        }
      }
    }, cfg)]);
  }
});