/*
 * File: app/view/pnlCategorias.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.view.pnlCategorias', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.pnlcategorias',

  requires: [
    'Bud.view.pnlVistaGeneralViewModel8',
    'Bud.view.pnlVistaGeneralViewController8',
    'Ext.grid.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.grid.column.Column',
    'Ext.view.Table',
    'Ext.form.field.Display'
  ],

  controller: 'pnlcategorias',
  viewModel: {
    type: 'pnlcategorias'
  },
  height: 627,
  id: 'pnlCategorias',
  width: 994,
  layout: 'fit',

  items: [
    {
      xtype: 'gridpanel',
      id: 'grdCategorias',
      title: 'Categorías',
      columnLines: true,
      store: 'categoriasStore',
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              iconCls: 'x-fa fa-plus',
              text: 'Insertar',
              listeners: {
                click: 'onBtnIngresosClick'
              }
            },
            {
              xtype: 'button',
              iconCls: 'x-fas fa-edit',
              text: 'Modificar'
            },
            {
              xtype: 'button',
              iconCls: 'x-fa fa-minus',
              text: 'Eliminar'
            }
          ]
        },
        {
          xtype: 'toolbar',
          dock: 'bottom',
          padding: 0,
          items: [
            {
              xtype: 'displayfield',
              value: '0 ítems'
            }
          ]
        }
      ],
      columns: [
        {
          xtype: 'gridcolumn',
          renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
            return (value === 'I' ? 'Ingreso' : (value === 'G' ? 'Gasto' : 'Meta'));
          },
          width: '25%',
          dataIndex: 'tipo_ingreso_gasto_meta',
          text: 'Tipo'
        },
        {
          xtype: 'gridcolumn',
          width: '75%',
          dataIndex: 'nombre_tipo_ingreso_gasto_meta',
          text: 'Descripción'
        }
      ]
    }
  ],
  listeners: {
    afterrender: 'onPnlCategoriasAfterRender'
  }

});