/*
 * File: app/view/vpMain.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.view.vpMain', {
  extend: 'Ext.container.Viewport',
  alias: 'widget.vpmain',

  requires: [
    'Bud.view.vpMainViewModel',
    'Bud.view.VpMainViewController',
    'Ext.plugin.Responsive',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.toolbar.Fill',
    'Ext.list.Tree'
  ],

  controller: 'vpMainViewController',
  viewModel: {
    type: 'vpmain'
  },
  height: 250,
  id: 'vpMain',
  width: 400,
  responsiveFormulas: {
    large: 'width > 1360',
    medium: 'width > 990 && width <= 1360',
    small: 'width > 768 && width <= 990',
    xsmall: 'width <= 768'
  },

  layout: {
    type: 'vbox',
    align: 'stretch'
  },
  items: [
    {
      xtype: 'toolbar',
      height: 50,
      padding: 0,
      items: [
        {
          xtype: 'component',
          cls: 'txtCabecera',
          dock: 'top',
          id: 'cmpHeaderBud',
          style: 'background-color: #005d8e;',
          width: 195,
          responsiveConfig: {
            xsmall: {
              width: 50,
              html: '<img src="assets/img/logo_solo_bud.jpg" width="50">'
            },
            small: {
              width: 50,
              html: '<img src="assets/img/logo_solo_bud.jpg" width="50">'
            },
            medium: {
              width: 190,
              html: '<img src="assets/img/logo.jpg" width="190">'
            },
            large: {
              width: 195,
              html: '<img src="assets/img/logo.jpg" width="195">'
            }
          },
          plugins: [
            {
              ptype: 'responsive'
            }
          ]
        },
        {
          xtype: 'button',
          iconCls: 'x-fa fa-bars',
          listeners: {
            click: 'onBtnToggle'
          }
        },
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          responsiveConfig: {
            xsmall: {
              text: ''
            },
            small: {
              text: ''
            },
            medium: {
              text: 'Salir'
            },
            large: {
              text: 'Salir'
            }
          },
          iconCls: 'x-fa fa-times-circle',
          text: 'Salir',
          listeners: {
            click: 'onBtnSalirClick'
          },
          plugins: [
            {
              ptype: 'responsive'
            }
          ]
        }
      ]
    },
    {
      xtype: 'container',
      flex: 1,
      layout: {
        type: 'hbox',
        align: 'stretch'
      },
      items: [
        {
          xtype: 'treelist',
          id: 'tlMenu',
          ui: 'nav',
          width: 195,
          expanderFirst: false,
          expanderOnly: false,
          store: 'menuStore',
          listeners: {
            selectionchange: 'onTlMenuSelectionChange'
          }
        },
        {
          xtype: 'container',
          flex: 1,
          id: 'cntCentral',
          layout: 'fit'
        }
      ]
    }
  ],
  listeners: {
    afterrender: 'onVpMainAfterRender'
  },
  plugins: [
    {
      ptype: 'responsive'
    }
  ]

});