/*
 * File: app/view/VpMainViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.view.VpMainViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.vpMainViewController',

  onBtnToggle: function(button, e, eOpts) {
    menu = Ext.getCmp('tlMenu');
    if (menu.getMicro())
    {
      menu.setMicro(false);
      menu.setWidth(195);
      Ext.getCmp('cmpHeader').setWidth(195);
      Ext.getCmp('cmpHeader').setHtml('<img src="assets/img/logo.jpg" width="195">');
    }
    else
    {
      menu.setMicro(true);
      menu.setWidth(50);
      Ext.getCmp('cmpHeader').setWidth(50);
      Ext.getCmp('cmpHeader').setHtml('<img src="assets/img/logo_solo_bud.jpg" width="50">');
    }
  },

  onBtnSalirClick: function(button, e, eOpts) {
    Bud.controller.Funciones.exitApp();
  },

  onTlMenuSelectionChange: function(treelist, record, eOpts) {
    if(record.data.itemId)
    {
      Bud.controller.Funciones.openPanel(record.data.itemId);
    }
  },

  onVpMainAfterRender: function(component, eOpts) {
    Bud.controller.Funciones.openPanel('pnlVistaGeneral');
  }

});
