/*
 * File: app/view/winCategorias.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.view.winCategorias', {
  extend: 'Ext.window.Window',
  alias: 'widget.wincategorias',

  requires: [
    'Bud.view.winCategoriasViewModel',
    'Bud.view.winCategoriasViewController',
    'Ext.form.Panel',
    'Ext.form.FieldSet',
    'Ext.form.field.ComboBox',
    'Ext.button.Button',
    'Ext.form.field.Hidden'
  ],

  controller: 'wincategorias',
  viewModel: {
    type: 'wincategorias'
  },
  constrain: true,
  height: 198,
  id: 'winCategorias',
  resizable: false,
  width: 368,
  layout: 'fit',
  closable: false,
  title: 'Categorías',

  items: [
    {
      xtype: 'form',
      id: 'frmCategorias',
      resizable: true,
      layout: 'fit',
      fieldDefaults: {
        labelWidth: 90,
        labelAlign: 'right',
        msgTarget: 'side',
        anchor: '100%',
        margin: '0 0 5 0',
        msgTarget: 'qtip'
      },
      items: [
        {
          xtype: 'fieldset',
          margin: 0,
          items: [
            {
              xtype: 'combobox',
              anchor: '100%',
              margin: '5 0 5 0',
              fieldLabel: 'Tipo',
              name: 'tipo_ingreso_gasto_meta',
              allowBlank: false,
              store: [
                [
                  'I',
                  'Ingreso'
                ],
                [
                  'G',
                  'Gasto'
                ],
                [
                  'M',
                  'Meta'
                ]
              ]
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Descripción',
              name: 'nombre_tipo_ingreso_gasto_meta',
              allowBlank: false
            },
            {
              xtype: 'container',
              margin: '20 40 0 40',
              layout: 'fit',
              items: [
                {
                  xtype: 'button',
                  text: 'Grabar',
                  listeners: {
                    click: 'onBtnGrabarClick'
                  }
                },
                {
                  xtype: 'button',
                  margin: '5 0 0 0',
                  text: 'Cerrar',
                  listeners: {
                    click: 'onBtnCerrarClick'
                  }
                }
              ]
            },
            {
              xtype: 'hiddenfield',
              anchor: '100%',
              fieldLabel: 'Label',
              name: 'id_tipo_ingreso_gasto_meta'
            }
          ]
        }
      ]
    }
  ],
  listeners: {
    afterrender: 'onWinCategoriasAfterRender'
  }

});