/*
 * File: app/view/winLogin.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.view.winLogin', {
  extend: 'Ext.window.Window',
  alias: 'widget.winlogin',

  requires: [
    'Bud.view.winLoginViewModel',
    'Bud.view.winLoginViewController',
    'Ext.form.Panel',
    'Ext.form.field.Text',
    'Ext.button.Button'
  ],

  controller: 'winlogin',
  viewModel: {
    type: 'winlogin'
  },
  modal: true,
  autoShow: true,
  draggable: false,
  height: 249,
  id: 'winLogin',
  resizable: false,
  width: 358,
  closable: false,

  layout: {
    type: 'vbox',
    align: 'stretch'
  },
  items: [
    {
      xtype: 'component',
      height: 85,
      html: '<div align="center"><img src="assets/img/logo.jpg" alt="logo" height="80"></div>',
      style: 'background-color:#005d8e;'
    },
    {
      xtype: 'form',
      id: 'frmLogin',
      bodyPadding: 10,
      items: [
        {
          xtype: 'textfield',
          anchor: '100%',
          id: 'txtMail',
          inputType: 'email',
          allowBlank: false,
          emptyText: 'E-mail'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          id: 'txtClave',
          inputType: 'password',
          allowBlank: false,
          emptyText: 'Clave',
          enableKeyEvents: true,
          listeners: {
            specialkey: 'onTxtClaveSpecialkey'
          }
        },
        {
          xtype: 'container',
          layout: 'fit',
          items: [
            {
              xtype: 'button',
              text: 'Ingresar',
              listeners: {
                click: 'onBtnIngresarClick'
              }
            }
          ]
        }
      ]
    }
  ]

});