/*
 * File: app/view/winLoginViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.view.winLoginViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.winlogin',

  onBtnIngresarClick: function(button, e, eOpts) {
    Ext.create('Bud.view.vpMain');
    Ext.getCmp('winLogin').destroy();
  }

});
