/*
 * File: app/view/winLoginViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.view.winLoginViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.winlogin',

  onTxtClaveSpecialkey: function(field, e, eOpts) {
    if(e.getKey() == e.ENTER)
    this.onBtnIngresarClick();
  },

  onBtnIngresarClick: function(button, e, eOpts) {
    const forma = Ext.getCmp('frmLogin').getForm();
    const storage = Ext.util.LocalStorage.get('main');
    const user = CONFIG.user;
    const pass = CONFIG.pass;
    const base64Credentials = btoa(user+':'+pass);


    if(forma.isValid())
    {
      Ext.Ajax.request
      (
      {
        url: CONFIG.apiUrl + 'loginbud',
        method: 'GET',
        params: {
          usr: Ext.getCmp('txtMail').getValue(),
          pwd: Ext.getCmp('txtClave').getValue()
        },
        headers: {
          'Authorization': 'Basic ' + base64Credentials
        },
        callback: function(obj, success, response)
        {
          if(success)
          {
            let res = Ext.JSON.decode(response.responseText);
            IDUSER = res.id_usuario;
            storage.setItem('token', res.token);
            Ext.create('Bud.view.vpMain');
            Ext.getCmp('winLogin').destroy();
          }
          else
          Bud.controller.Funciones.showMessg('INFO', 'Mail o clave incorrectos');
        }
      }
      );
    }
  }

});
