/*
 * File: app/model/categoriasModel.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bud.model.categoriasModel', {
  extend: 'Ext.data.Model',

  requires: [
    'Ext.data.field.Field'
  ],

  idProperty: 'id_tipo_ingreso_gasto_meta',

  fields: [
    {
      name: 'id_tipo_ingreso_gasto_meta'
    },
    {
      name: 'id_usuario'
    },
    {
      name: 'tipo_ingreso_gasto_meta'
    },
    {
      name: 'nombre_tipo_ingreso_gasto_meta'
    }
  ]
});